In [1]:
import numpy as np

In [2]:
arr1 = np.array([100,200,300,400])

In [3]:
arr1

array([100, 200, 300, 400])

In [4]:
print(arr1)

[100 200 300 400]


In [5]:
list1 = [100, 200, 300, 400]

In [6]:
list1

[100, 200, 300, 400]

In [7]:
type(list1)

list

In [8]:
arr2 = np.array([[10,20,30],[100,200,300],[11,22,33]])

In [9]:
arr2

array([[ 10,  20,  30],
       [100, 200, 300],
       [ 11,  22,  33]])

In [10]:
arr2.ndim

2

In [11]:
arr2.shape

(3, 3)

In [12]:
arr2.size

9

In [13]:
arr2.dtype

dtype('int32')

In [14]:
arr2.itemsize

4

In [15]:
ary_one = np.ones((4,5), dtype = "int")

In [16]:
ary_one

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [17]:
ary_one.dtype

dtype('int32')

In [18]:
ary_3d = np.ones((2,4,6), dtype = "int")

In [19]:
ary_3d

array([[[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]]])

In [20]:
ary_zero = np.zeros((3,5,6))

In [21]:
ary_zero

array([[[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]]])

In [22]:
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [23]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [24]:
np.eye(4,6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.]])

In [25]:
np.eye(4,6, k=1)

array([[0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.]])

In [26]:
np.eye(4,6, k=2)

array([[0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [27]:
np.eye(4,6, k=-2)

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.]])

In [28]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [29]:
np.linspace(1,2,100, retstep=True)

(array([1.        , 1.01010101, 1.02020202, 1.03030303, 1.04040404,
        1.05050505, 1.06060606, 1.07070707, 1.08080808, 1.09090909,
        1.1010101 , 1.11111111, 1.12121212, 1.13131313, 1.14141414,
        1.15151515, 1.16161616, 1.17171717, 1.18181818, 1.19191919,
        1.2020202 , 1.21212121, 1.22222222, 1.23232323, 1.24242424,
        1.25252525, 1.26262626, 1.27272727, 1.28282828, 1.29292929,
        1.3030303 , 1.31313131, 1.32323232, 1.33333333, 1.34343434,
        1.35353535, 1.36363636, 1.37373737, 1.38383838, 1.39393939,
        1.4040404 , 1.41414141, 1.42424242, 1.43434343, 1.44444444,
        1.45454545, 1.46464646, 1.47474747, 1.48484848, 1.49494949,
        1.50505051, 1.51515152, 1.52525253, 1.53535354, 1.54545455,
        1.55555556, 1.56565657, 1.57575758, 1.58585859, 1.5959596 ,
        1.60606061, 1.61616162, 1.62626263, 1.63636364, 1.64646465,
        1.65656566, 1.66666667, 1.67676768, 1.68686869, 1.6969697 ,
        1.70707071, 1.71717172, 1.72727273, 1.73

In [30]:
ary1 = np.random.rand(4,5)

In [31]:
ary1

array([[0.25965141, 0.75657339, 0.50025613, 0.04029012, 0.57549151],
       [0.50351204, 0.77274141, 0.00406913, 0.14048937, 0.15007779],
       [0.48097472, 0.41837806, 0.97945913, 0.94828661, 0.02483335],
       [0.68883386, 0.570191  , 0.99319241, 0.81333453, 0.3132534 ]])

In [32]:
ary2 = np.random.rand(3,4,5)

In [33]:
ary2

array([[[0.61598896, 0.95214786, 0.19552978, 0.54923186, 0.7595043 ],
        [0.41850222, 0.53123953, 0.14625992, 0.84779388, 0.98101131],
        [0.73602975, 0.36228038, 0.79019932, 0.33157746, 0.33330137],
        [0.23448069, 0.4963031 , 0.1867735 , 0.93618514, 0.2488705 ]],

       [[0.00522394, 0.92276945, 0.38188497, 0.69325177, 0.41447131],
        [0.94476638, 0.26222342, 0.25144767, 0.01838441, 0.1683121 ],
        [0.41365376, 0.14569217, 0.11104413, 0.23494026, 0.13902367],
        [0.25467866, 0.28227771, 0.92785069, 0.77443812, 0.64206019]],

       [[0.0031767 , 0.21011528, 0.97909011, 0.13419178, 0.79059445],
        [0.99715399, 0.06330093, 0.49225981, 0.35871224, 0.45610925],
        [0.46361827, 0.94890693, 0.87640209, 0.82073114, 0.5362048 ],
        [0.16802666, 0.90780582, 0.72619481, 0.62203957, 0.09225997]]])

In [34]:
np.random.randn(4,5)

array([[ 1.07131062, -0.5896657 ,  0.17035699, -0.41387559, -0.28780706],
       [-0.27537739,  1.68352911, -1.50568318,  0.0277852 ,  2.18527215],
       [-0.07839203, -0.14603728, -0.41534146, -1.23722139, -0.67881243],
       [ 1.20283287,  0.11523235,  1.19593164, -1.80220294,  0.00287045]])

In [35]:
ary3 = np.random.randn(2,3,5)

In [36]:
ary3

array([[[ 0.47313609, -0.00877317, -0.65621199,  0.71649347,
          0.81498589],
        [ 0.15648465, -0.07044669,  1.33833903,  1.33987533,
          1.63921716],
        [ 0.80724944,  0.45936945,  0.26284567, -0.49073327,
          1.66931364]],

       [[ 1.22780856, -1.57973343, -0.81684993,  1.53038302,
         -0.3696001 ],
        [ 0.39798649,  0.19937215,  0.468239  ,  0.88282709,
          1.08982699],
        [-0.20716364,  0.5876825 ,  0.07069172, -0.68000672,
          0.91734211]]])

In [37]:
ary3.ndim

3

In [38]:
ary3.shape

(2, 3, 5)

In [39]:
ary3.size

30

In [40]:
ary3.dtype

dtype('float64')

In [41]:
a1 = np.random.randint(10,50,(4,6))

In [42]:
a1

array([[27, 37, 22, 12, 49, 40],
       [16, 15, 34, 41, 36, 48],
       [45, 49, 20, 27, 36, 45],
       [40, 33, 41, 41, 49, 17]])

In [43]:
a1.size

24

In [44]:
a1.shape

(4, 6)

In [45]:
a1[1,3]

41

In [46]:
a1[1][3]

41

In [47]:
a1[2,3]

27

In [48]:
a1[1:3:1 , 1:5:1]

array([[15, 34, 41, 36],
       [49, 20, 27, 36]])

In [49]:
a1[0:3:1 , 0:4:1]

array([[27, 37, 22, 12],
       [16, 15, 34, 41],
       [45, 49, 20, 27]])

In [50]:
a1[0:3 : 2  ,  1 : 5 : 1  ]

array([[37, 22, 12, 49],
       [49, 20, 27, 36]])

In [51]:
a2 = np.random.randint(10,80,(2,4,6))

In [52]:
a2

array([[[27, 30, 41, 39, 54, 75],
        [47, 39, 58, 17, 19, 61],
        [65, 21, 43, 46, 76, 13],
        [73, 70, 58, 47, 59, 27]],

       [[24, 51, 23, 33, 10, 60],
        [31, 41, 67, 58, 63, 45],
        [10, 48, 40, 72, 77, 42],
        [14, 72, 42, 27, 31, 75]]])

In [53]:
a2.ndim

3

In [54]:
a2[0,2,3]

46

In [55]:
a2 [ 0:1 , 1:4:1 , 1:4:1]

array([[[39, 58, 17],
        [21, 43, 46],
        [70, 58, 47]]])

In [56]:
a2 [0:2:1 , 0:3:2 , 1:5:1]

array([[[30, 41, 39, 54],
        [21, 43, 46, 76]],

       [[51, 23, 33, 10],
        [48, 40, 72, 77]]])

In [57]:
a2[  0:2:1   ,   1 : 3 : 1       ,    1 : 4 : 1    ]

array([[[39, 58, 17],
        [21, 43, 46]],

       [[41, 67, 58],
        [48, 40, 72]]])

In [58]:
a3 = np.random.randint(100,200,(2,3,4,6))

In [59]:
a3

array([[[[170, 114, 149, 109, 105, 110],
         [175, 101, 141, 164, 123, 117],
         [119, 193, 193, 149, 164, 143],
         [177, 154, 174, 124, 127, 147]],

        [[134, 168, 159, 158, 172, 138],
         [139, 161, 156, 146, 169, 131],
         [113, 195, 113, 102, 176, 170],
         [148, 123, 198, 193, 189, 170]],

        [[141, 100, 185, 188, 185, 108],
         [199, 172, 106, 189, 113, 126],
         [178, 153, 144, 178, 191, 130],
         [179, 124, 109, 194, 101, 160]]],


       [[[139, 199, 184, 155, 193, 146],
         [184, 137, 178, 129, 163, 100],
         [128, 114, 139, 175, 184, 118],
         [135, 186, 133, 130, 190, 141]],

        [[143, 161, 188, 197, 158, 131],
         [124, 126, 112, 117, 126, 125],
         [188, 197, 178, 189, 113, 123],
         [158, 184, 188, 146, 172, 167]],

        [[116, 186, 116, 127, 146, 179],
         [186, 147, 187, 153, 140, 123],
         [193, 100, 152, 107, 104, 159],
         [157, 105, 133, 191, 137, 168]]]])

In [60]:
a3.ndim

4

In [61]:
list1 = [10,50,80,90]

In [62]:
np.random.choice(list1, (4,6), p = [0.2,0,0.3,0.5])

array([[90, 90, 80, 90, 90, 90],
       [80, 10, 80, 90, 90, 90],
       [90, 10, 90, 90, 90, 80],
       [80, 90, 80, 10, 90, 80]])

In [63]:
np1 = np.arange(11,19)

In [64]:
np1

array([11, 12, 13, 14, 15, 16, 17, 18])

In [65]:
a4 = np.random.randint(10,52,(2,2,4,6))

In [66]:
a4

array([[[[43, 17, 48, 15, 27, 37],
         [11, 24, 34, 15, 51, 25],
         [47, 12, 29, 23, 16, 10],
         [43, 32, 34, 14, 13, 39]],

        [[14, 31, 38, 11, 18, 22],
         [14, 30, 36, 23, 47, 32],
         [18, 48, 12, 51, 21, 51],
         [15, 19, 51, 33, 31, 41]]],


       [[[12, 44, 38, 12, 24, 44],
         [41, 20, 15, 17, 47, 15],
         [22, 41, 46, 28, 16, 43],
         [22, 14, 15, 12, 19, 37]],

        [[37, 16, 26, 47, 48, 11],
         [40, 47, 29, 17, 28, 51],
         [30, 47, 51, 38, 38, 38],
         [18, 33, 26, 33, 46, 36]]]])

In [67]:
a4.shape

(2, 2, 4, 6)

In [68]:
a4[ 0:2:1   , 0:2:1   , 1:3:1    , 1:5:1   ]

array([[[[24, 34, 15, 51],
         [12, 29, 23, 16]],

        [[30, 36, 23, 47],
         [48, 12, 51, 21]]],


       [[[20, 15, 17, 47],
         [41, 46, 28, 16]],

        [[47, 29, 17, 28],
         [47, 51, 38, 38]]]])

In [69]:
a5 = np.random.randint(10,60,(3,4,6))

In [70]:
a5

array([[[14, 48, 17, 16, 48, 18],
        [36, 14, 47, 18, 20, 11],
        [18, 20, 59, 36, 57, 43],
        [44, 11, 20, 43, 56, 27]],

       [[35, 43, 34, 40, 21, 22],
        [38, 53, 35, 59, 28, 31],
        [20, 35, 59, 38, 25, 18],
        [43, 49, 27, 38, 56, 11]],

       [[43, 54, 47, 15, 43, 44],
        [50, 32, 58, 52, 15, 15],
        [58, 43, 10, 25, 10, 47],
        [21, 51, 11, 50, 59, 28]]])

In [71]:
a5[ 0:3:2  , 1:4:1   , 1:4:1   ]

array([[[14, 47, 18],
        [20, 59, 36],
        [11, 20, 43]],

       [[32, 58, 52],
        [43, 10, 25],
        [51, 11, 50]]])

## ADVANCED INDEXING

In [72]:
b1 = np.arange(10,30)

In [73]:
b1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [74]:
b1[4]

14

In [75]:
b1[5:11:1]

array([15, 16, 17, 18, 19, 20])

In [76]:
b1[5:11:2]

array([15, 17, 19])

In [77]:
l1 = [1,5,6,8,13,15]

In [78]:
b1[l1]

array([11, 15, 16, 18, 23, 25])

In [79]:
b1[[1,5,6,8,13,15]]

array([11, 15, 16, 18, 23, 25])

In [80]:
b2 = np.random.randint(10,50,(4,5))

In [81]:
b2

array([[35, 24, 29, 36, 43],
       [18, 31, 34, 46, 15],
       [21, 48, 46, 14, 26],
       [32, 37, 31, 41, 20]])

In [82]:
b2[1,3]

46

In [83]:
b2[ 1: 3 : 1  ,   1 : 4 : 1  ]

array([[31, 34, 46],
       [48, 46, 14]])

In [84]:
rindex = [2,1,2,0,3]

In [85]:
cindex = [0,1,3,2,4]

In [86]:
b2[ rindex, cindex]

array([21, 31, 14, 29, 20])

In [87]:
b2[ [2,1,2,0,3]  ,  [0,1,3,2,4]   ]

array([21, 31, 14, 29, 20])

In [88]:
b3 = np.random.randint(20,50,(2,4,6))

In [89]:
b3

array([[[42, 35, 32, 46, 38, 43],
        [39, 43, 28, 38, 27, 25],
        [41, 45, 47, 32, 25, 36],
        [24, 30, 28, 40, 38, 22]],

       [[26, 49, 21, 28, 35, 30],
        [22, 20, 21, 28, 38, 48],
        [49, 22, 22, 47, 33, 35],
        [29, 47, 47, 48, 32, 43]]])

In [90]:
b3[[0,1,0,1,0,1]     , [3,2,0,2,2,1]        ,[4,1,0,5,2,3,]    ]

array([38, 22, 42, 35, 47, 28])

## BOOLEAN INDEXING

In [91]:
c1 = np.random.randint(70,150,(50))

In [92]:
c1

array([119,  78,  72,  77,  93, 140, 133,  76, 145, 110, 126, 124, 142,
        90, 102,  93, 122, 119, 129, 120, 106, 125, 121, 136,  73,  93,
       101,  92, 117, 148, 115, 118,  70, 138, 131,  70, 103,  71, 131,
       130, 148,  81, 140, 113, 132, 127,  71,  93,  75,  80])

In [93]:
f1 = c1 < 100

In [94]:
f1

array([False,  True,  True,  True,  True, False, False,  True, False,
       False, False, False, False,  True, False,  True, False, False,
       False, False, False, False, False, False,  True,  True, False,
        True, False, False, False, False,  True, False, False,  True,
       False,  True, False, False, False,  True, False, False, False,
       False,  True,  True,  True,  True])

In [95]:
c1[f1]

array([78, 72, 77, 93, 76, 90, 93, 73, 93, 92, 70, 70, 71, 81, 71, 93, 75,
       80])

In [96]:
c1[c1 < 100]

array([78, 72, 77, 93, 76, 90, 93, 73, 93, 92, 70, 70, 71, 81, 71, 93, 75,
       80])

In [97]:
c2 = np.random.randint(10,300,(6,8))

In [98]:
c2

array([[282, 193,  58, 185,  78,  62, 173,  53],
       [ 63, 228, 226, 245, 179,  55,  48,  16],
       [260, 255, 252, 216, 212, 288,  48, 259],
       [ 33,  16, 240, 152, 286,  90, 173, 259],
       [269, 115, 119, 286,  38,  84, 281, 251],
       [143, 244, 196, 299, 169,  43, 230, 105]])

In [99]:
c2[c2<100]

array([58, 78, 62, 53, 63, 55, 48, 16, 48, 33, 16, 90, 38, 84, 43])

In [100]:
c2 > 200

array([[ True, False, False, False, False, False, False, False],
       [False,  True,  True,  True, False, False, False, False],
       [ True,  True,  True,  True,  True,  True, False,  True],
       [False, False,  True, False,  True, False, False,  True],
       [ True, False, False,  True, False, False,  True,  True],
       [False,  True, False,  True, False, False,  True, False]])

In [101]:
c2[c2>200]

array([282, 228, 226, 245, 260, 255, 252, 216, 212, 288, 259, 240, 286,
       259, 269, 286, 281, 251, 244, 299, 230])

In [102]:
#c2 > 100 and c2 < 200 Error

In [103]:
f2 = (c2 > 100) & (c2 < 200)

In [104]:
f2

array([[False,  True, False,  True, False, False,  True, False],
       [False, False, False, False,  True, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False,  True, False, False,  True, False],
       [False,  True,  True, False, False, False, False, False],
       [ True, False,  True, False,  True, False, False,  True]])

In [105]:
c2[f2]

array([193, 185, 173, 179, 152, 173, 115, 119, 143, 196, 169, 105])

In [106]:
(c2 < 100)  |  (c2 > 200)

array([[ True, False,  True, False,  True,  True, False,  True],
       [ True,  True,  True,  True, False,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True, False,  True,  True, False,  True],
       [ True, False, False,  True,  True,  True,  True,  True],
       [False,  True, False,  True, False,  True,  True, False]])

In [107]:
c2[(c2 < 100)  |  (c2 > 200)]

array([282,  58,  78,  62,  53,  63, 228, 226, 245,  55,  48,  16, 260,
       255, 252, 216, 212, 288,  48, 259,  33,  16, 240, 286,  90, 259,
       269, 286,  38,  84, 281, 251, 244, 299,  43, 230])

## Operations

In [108]:
d1 = np.arange(1,6)

In [109]:
d1

array([1, 2, 3, 4, 5])

In [110]:
d2 = np.arange(11,18)

In [111]:
d2

array([11, 12, 13, 14, 15, 16, 17])

In [112]:
d1.shape

(5,)

In [113]:
d2.shape

(7,)

In [114]:
# d1 + d2  Error:operands could not be broadcast together with shapes (5,) (7,) 


In [115]:
d3 = np.arange(11,16)

In [116]:
d3

array([11, 12, 13, 14, 15])

In [117]:
d1.shape

(5,)

In [118]:
d3.shape

(5,)

In [119]:
d1 + d3

array([12, 14, 16, 18, 20])

In [120]:
e1 = np.random.randint(1,10,(2,2))

In [121]:
e2 = np.random.randint(1,10,(2,2))

In [122]:
e1

array([[9, 3],
       [9, 5]])

In [123]:
e2

array([[5, 1],
       [7, 4]])

In [124]:
e1.ndim

2

In [125]:
e2.ndim

2

In [126]:
e1.shape

(2, 2)

In [127]:
e2.shape

(2, 2)

In [128]:
e1 + e2

array([[14,  4],
       [16,  9]])

In [129]:
e3 = np.random.randint(1,10,(2,1))

In [130]:
e3

array([[9],
       [2]])

In [131]:
e3.ndim

2

In [132]:
e3.shape

(2, 1)

In [133]:
e1.shape

(2, 2)

In [134]:
e1 + e3

array([[18, 12],
       [11,  7]])

In [135]:
e4 = np.random.randint(1,10,(3,1))

In [136]:
e4.shape

(3, 1)

In [137]:
e4.ndim

2

In [138]:
e2.ndim

2

In [139]:
e2.shape

(2, 2)

In [140]:
# e4 + e2 Error: operands could not be broadcast together with shapes (3,1) (2,2) 


In [141]:
e4

array([[1],
       [2],
       [9]])

In [142]:
e2

array([[5, 1],
       [7, 4]])

In [143]:
e2 + 5

array([[10,  6],
       [12,  9]])

In [144]:
d1

array([1, 2, 3, 4, 5])

In [145]:
d1 + 5

array([ 6,  7,  8,  9, 10])

In [146]:
e2

array([[5, 1],
       [7, 4]])

In [147]:
e3

array([[9],
       [2]])

In [148]:
e2.ndim

2

In [149]:
e3.ndim

2

In [150]:
e2.shape

(2, 2)

In [151]:
e3.shape

(2, 1)

In [152]:
e2 + e3

array([[14, 10],
       [ 9,  6]])

In [153]:
e2.shape

(2, 2)

In [154]:
e4.shape

(3, 1)

In [155]:
e2 + e4

ValueError: operands could not be broadcast together with shapes (2,2) (3,1) 

In [156]:
e4.ndim

2

In [157]:
f1 = np.random.randint(10,20,(2,3,6))

In [158]:
f1

array([[[10, 14, 12, 16, 16, 18],
        [14, 14, 18, 16, 12, 18],
        [19, 10, 19, 12, 16, 12]],

       [[15, 11, 18, 15, 15, 18],
        [17, 12, 16, 19, 17, 11],
        [11, 10, 14, 13, 11, 11]]])

In [159]:
f1.shape

(2, 3, 6)

In [160]:
f1.ndim

3

In [161]:
f2 = np.random.randint(20,40,(2,1,6))

In [162]:
f2.shape

(2, 1, 6)

In [163]:
display(f1.shape, f2.shape)

(2, 3, 6)

(2, 1, 6)

In [164]:
f1

array([[[10, 14, 12, 16, 16, 18],
        [14, 14, 18, 16, 12, 18],
        [19, 10, 19, 12, 16, 12]],

       [[15, 11, 18, 15, 15, 18],
        [17, 12, 16, 19, 17, 11],
        [11, 10, 14, 13, 11, 11]]])

In [165]:
f2

array([[[33, 36, 24, 31, 32, 23]],

       [[32, 20, 23, 30, 25, 31]]])

In [166]:
f1+f2

array([[[43, 50, 36, 47, 48, 41],
        [47, 50, 42, 47, 44, 41],
        [52, 46, 43, 43, 48, 35]],

       [[47, 31, 41, 45, 40, 49],
        [49, 32, 39, 49, 42, 42],
        [43, 30, 37, 43, 36, 42]]])

In [167]:
f1.ndim

3

In [168]:
f1.shape

(2, 3, 6)

In [169]:
e4.shape

(3, 1)

In [170]:
f1

array([[[10, 14, 12, 16, 16, 18],
        [14, 14, 18, 16, 12, 18],
        [19, 10, 19, 12, 16, 12]],

       [[15, 11, 18, 15, 15, 18],
        [17, 12, 16, 19, 17, 11],
        [11, 10, 14, 13, 11, 11]]])

In [171]:
e4

array([[1],
       [2],
       [9]])

In [172]:
f1 + e4

array([[[11, 15, 13, 17, 17, 19],
        [16, 16, 20, 18, 14, 20],
        [28, 19, 28, 21, 25, 21]],

       [[16, 12, 19, 16, 16, 19],
        [19, 14, 18, 21, 19, 13],
        [20, 19, 23, 22, 20, 20]]])

In [173]:
g1  = np.random.randint(10,50,(2,3,4,5))


In [174]:
g1.ndim

4

In [175]:
g1.shape

(2, 3, 4, 5)

In [176]:
g2 = np.random.randint(10,50,(4,5))

In [177]:
g2

array([[31, 17, 36, 47, 35],
       [19, 11, 49, 10, 49],
       [17, 16, 34, 20, 47],
       [42, 25, 42, 26, 24]])

In [178]:
g1

array([[[[11, 16, 25, 23, 44],
         [11, 24, 13, 23, 21],
         [33, 11, 34, 48, 13],
         [21, 10, 33, 33, 44]],

        [[48, 31, 16, 34, 33],
         [14, 35, 46, 20, 46],
         [32, 10, 35, 12, 16],
         [13, 22, 34, 21, 34]],

        [[34, 44, 33, 47, 15],
         [13, 20, 38, 48, 31],
         [13, 10, 24, 18, 20],
         [30, 37, 20, 24, 18]]],


       [[[35, 48, 14, 43, 49],
         [41, 38, 11, 34, 35],
         [20, 39, 47, 22, 16],
         [10, 17, 19, 15, 43]],

        [[37, 30, 41, 28, 14],
         [12, 30, 21, 41, 23],
         [29, 39, 21, 17, 49],
         [16, 24, 37, 29, 18]],

        [[13, 35, 10, 20, 45],
         [42, 17, 36, 23, 38],
         [24, 43, 17, 26, 38],
         [19, 25, 22, 15, 44]]]])

In [179]:
display(g1.shape, g2.shape)

(2, 3, 4, 5)

(4, 5)

In [180]:
g1+g2

array([[[[42, 33, 61, 70, 79],
         [30, 35, 62, 33, 70],
         [50, 27, 68, 68, 60],
         [63, 35, 75, 59, 68]],

        [[79, 48, 52, 81, 68],
         [33, 46, 95, 30, 95],
         [49, 26, 69, 32, 63],
         [55, 47, 76, 47, 58]],

        [[65, 61, 69, 94, 50],
         [32, 31, 87, 58, 80],
         [30, 26, 58, 38, 67],
         [72, 62, 62, 50, 42]]],


       [[[66, 65, 50, 90, 84],
         [60, 49, 60, 44, 84],
         [37, 55, 81, 42, 63],
         [52, 42, 61, 41, 67]],

        [[68, 47, 77, 75, 49],
         [31, 41, 70, 51, 72],
         [46, 55, 55, 37, 96],
         [58, 49, 79, 55, 42]],

        [[44, 52, 46, 67, 80],
         [61, 28, 85, 33, 87],
         [41, 59, 51, 46, 85],
         [61, 50, 64, 41, 68]]]])